[tool.poetry]
name = "django-proj"
version = "0.1.0"
description = ""
authors = ["Adam <A.ergashev@internet.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.2.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
